---
- name: "Pre-Apache Config"
  hosts: "webhost"
  become: yes
  become_method: sudo
  tasks:
  - name: "Stop nginx"
    service:
      name: "{{ user }}"
      state: stopped
    ignore_errors: yes
- name: "Install EPEL, PHP and Apache"
  hosts: "webhost"
  become: yes
  become_method: sudo
  vars:
    apache_create_vhosts: false
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.php
    - geerlingguy.apache

- name: "Post-Apache Config"
  hosts: "webhost"
  become: yes
  become_method: sudo
  vars:
    apache_create_vhosts: false
    apache_vhosts_filename: "files/vhosts.conf"
  tasks:
    - name: "Remove Port 80 Listener added by role"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        state: absent
        regexp: "Listen 80"
    - name: "Update listening ports"
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: "#Listen 12.34.56.78:80"
        block: |
          Listen 81
          Listen 8008
    - name: "Add vhosts file"
      template:
        src: files/vhosts.conf
        dest: /etc/httpd/conf.d/vhosts.conf
    - name: "Create webroots"
      file:
        path: /var/www/{{item}}
        state: directory
      with_items:
        - "server1"
        - "server2"
    - name: "Add index pages"
      template:
        src: files/{{item}}.php
        dest: /var/www/{{item}}/index.php
      with_items:
        - "server1"
        - "server2"
    - name: "Restart Apache"
      service:
        name: httpd
        state: restarted

- name: "Install nginx"
  hosts: "webhost"
  become: yes
  become_method: sudo
  roles:
    - nginxinc.nginx

- name: "Post-nginx Config"
  hosts: "webhost"
  become: yes
  become_method: sudo
  tasks:
    - name: "Copy load balancer config"
      template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: "Restart nginx"
      service:
        name: nginx
        state: restarted

      
